require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/item_trocas", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # ItemTroca. As you add validations to ItemTroca, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ItemTroca.create! valid_attributes
      get item_trocas_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      item_troca = ItemTroca.create! valid_attributes
      get item_troca_url(item_troca)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_item_troca_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      item_troca = ItemTroca.create! valid_attributes
      get edit_item_troca_url(item_troca)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ItemTroca" do
        expect {
          post item_trocas_url, params: { item_troca: valid_attributes }
        }.to change(ItemTroca, :count).by(1)
      end

      it "redirects to the created item_troca" do
        post item_trocas_url, params: { item_troca: valid_attributes }
        expect(response).to redirect_to(item_troca_url(ItemTroca.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ItemTroca" do
        expect {
          post item_trocas_url, params: { item_troca: invalid_attributes }
        }.to change(ItemTroca, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post item_trocas_url, params: { item_troca: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested item_troca" do
        item_troca = ItemTroca.create! valid_attributes
        patch item_troca_url(item_troca), params: { item_troca: new_attributes }
        item_troca.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the item_troca" do
        item_troca = ItemTroca.create! valid_attributes
        patch item_troca_url(item_troca), params: { item_troca: new_attributes }
        item_troca.reload
        expect(response).to redirect_to(item_troca_url(item_troca))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        item_troca = ItemTroca.create! valid_attributes
        patch item_troca_url(item_troca), params: { item_troca: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested item_troca" do
      item_troca = ItemTroca.create! valid_attributes
      expect {
        delete item_troca_url(item_troca)
      }.to change(ItemTroca, :count).by(-1)
    end

    it "redirects to the item_trocas list" do
      item_troca = ItemTroca.create! valid_attributes
      delete item_troca_url(item_troca)
      expect(response).to redirect_to(item_trocas_url)
    end
  end
end
