require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/trocas", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Troca. As you add validations to Troca, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Troca.create! valid_attributes
      get trocas_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      troca = Troca.create! valid_attributes
      get troca_url(troca)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_troca_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      troca = Troca.create! valid_attributes
      get edit_troca_url(troca)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Troca" do
        expect {
          post trocas_url, params: { troca: valid_attributes }
        }.to change(Troca, :count).by(1)
      end

      it "redirects to the created troca" do
        post trocas_url, params: { troca: valid_attributes }
        expect(response).to redirect_to(troca_url(Troca.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Troca" do
        expect {
          post trocas_url, params: { troca: invalid_attributes }
        }.to change(Troca, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post trocas_url, params: { troca: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested troca" do
        troca = Troca.create! valid_attributes
        patch troca_url(troca), params: { troca: new_attributes }
        troca.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the troca" do
        troca = Troca.create! valid_attributes
        patch troca_url(troca), params: { troca: new_attributes }
        troca.reload
        expect(response).to redirect_to(troca_url(troca))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        troca = Troca.create! valid_attributes
        patch troca_url(troca), params: { troca: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested troca" do
      troca = Troca.create! valid_attributes
      expect {
        delete troca_url(troca)
      }.to change(Troca, :count).by(-1)
    end

    it "redirects to the trocas list" do
      troca = Troca.create! valid_attributes
      delete troca_url(troca)
      expect(response).to redirect_to(trocas_url)
    end
  end
end
